services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sustainabull
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sustainabull"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./sustainabull_backend
    container_name: sustainabull_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/sustainabull
      DJANGO_SETTINGS_MODULE: sustainabull_backend.settings
    ports:
      - "8000:8000"
    volumes:
      - ./sustainabull_backend:/app
      - backend_venv:/venv
    command: >
      sh -c "
        /venv/bin/python manage.py migrate --noinput &&
        /venv/bin/python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    platform: linux/arm64
    build: ./sustainabull_frontend
    container_name: sustainabull_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./sustainabull_frontend:/app
      # - /app/node_modules

volumes:
  db_data:
  backend_venv: