services:
  db:
    image: postgres:15
    container_name: sustainabull_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sustainabull
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: ./sustainabull_backend
    container_name: sustainabull_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/sustainabull
    ports:
      - "8000:8000"
    volumes:
      - ./sustainabull_backend:/app
      - backend_venv:/venv

  frontend:
    platform: linux/arm64
    build: ./sustainabull_frontend
    container_name: sustainabull_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./sustainabull_frontend:/app
      # - /app/node_modules

volumes:
  db_data:
  backend_venv:
