services:
  db:
    image: postgres:15
    container_name: sustainabull_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sustainabull
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # initdbフォルダがある前提でマウント

  backend:
    build: ./sustainabull_backend
    container_name: sustainabull_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/sustainabull
    ports:
      - "8000:8000"
    volumes:
      - ./sustainabull_backend:/sustainabull_backend  # backendコードのホットリロードを有効化

  frontend:
    build: ./sustainabull_frontend  # 正しいディレクトリ名に変更
    container_name: sustainabull_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./sustainabull_frontend:/app  # 正しいディレクトリをマウント
      # - /app/node_modules は不要（競合回避）

volumes:
  db_data:
