# version: "3.8"
services:
  frontend:
    build:
      context: ./sustainabull-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./sustainabull-project:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./sustainabull_backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "8000:8000"
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #     - POSTGRES_DB=mydb # Your database name
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
