services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=sustainabull
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./sustainabull_backend
    container_name: sustainabull_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sustainabull
    ports:
      - "8000:8000"
    volumes:
      - ./sustainabull_backend:/app
      - backend_venv:/venv

  frontend:
    platform: linux/arm64
    build: ./sustainabull_frontend
    container_name: sustainabull_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./sustainabull_frontend:/app
      # - /app/node_modules

volumes:
  postgres_data:
  backend_venv: