# Generated by Django 5.0.4 on 2025-03-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_item_user_gold_alter_user_password_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
