# Generated by Django 5.0.4 on 2025-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_inventoryitem_item_remove_inventoryitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gold',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
