# Generated by Django 5.0.4 on 2025-04-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopitem_remove_user_gold_user_coin_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coin',
            new_name='gold',
        ),
    ]
