# Generated by Django 5.0.4 on 2025-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
