# Generated by Django 5.0.4 on 2025-04-02 12:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='total_distance_traveled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cow',
            name='co2_emissions',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='exercise',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='mood',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='TransportationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('walk', 'Walk'), ('bike', 'Bike'), ('transit', 'Public Transit'), ('vehicle', 'Vehicle')], default='walk', max_length=20)),
                ('distance_meters', models.PositiveIntegerField()),
                ('xp_gained', models.PositiveIntegerField()),
                ('gold_gained', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_logs', to='shop.cow')),
            ],
        ),
    ]
